// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Blueprint41.DatastoreTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Blueprint41;
    using Blueprint41.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Domain_Data_Relationship : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"#nullable disable
#pragma warning disable S101 // Types should be named in PascalCase
#pragma warning disable CS8981 // Names should not be lower type only
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable VSSpell001 // Spell Check

using System;
using System.Collections.Generic;

using Blueprint41;
using Blueprint41.Query;
using Blueprint41.Events;

namespace ");
            
            #line 20 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.FullQueryNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\npublic partial class ");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL : RELATIONSHIP, IFromIn_");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL, IFromOut_");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
 if (DALRelation.InEntity == DALRelation.OutEntity) { 
            
            #line default
            #line hidden
            this.Write(", IFromAny_");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
 }
            
            #line default
            #line hidden
            this.Write("    {\r\n        public override string NEO4J_TYPE\r\n        {\r\n            get\r\n   " +
                    "         {\r\n                return \"");
            
            #line 28 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Neo4JRelationshipType));
            
            #line default
            #line hidden
            this.Write("\";\r\n            }\r\n        }\r\n        public override AliasResult RelationshipAli" +
                    "as { get; protected set; }\r\n        \r\n        internal ");
            
            #line 33 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL(Blueprint41.Query.Node parent, DirectionEnum direction) : base(parent, direc" +
                    "tion) { }\r\n\r\n        public ");
            
            #line 35 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Alias(out ");
            
            #line 35 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias)\r\n        {\r\n            alias = new ");
            
            #line 37 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS(this);\r\n            RelationshipAlias = alias;\r\n            return this;\r\n" +
                    "        } \r\n        public ");
            
            #line 41 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int maxHops)\r\n        {\r\n            return Repeat(1, maxHops);\r\n    " +
                    "    }\r\n        public new ");
            
            #line 45 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int minHops, int maxHops)\r\n        {\r\n            base.Repeat(minHops" +
                    ", maxHops);\r\n            return this;\r\n        }\r\n\r\n        IFromIn_");
            
            #line 51 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromIn_");
            
            #line 51 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Alias(out ");
            
            #line 51 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias)\r\n        {\r\n            return Alias(out alias);\r\n        }\r\n      " +
                    "  IFromOut_");
            
            #line 55 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromOut_");
            
            #line 55 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Alias(out ");
            
            #line 55 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias)\r\n        {\r\n            return Alias(out alias);\r\n        }\r\n      " +
                    "  IFromIn_");
            
            #line 59 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromIn_");
            
            #line 59 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int maxHops)\r\n        {\r\n            return Repeat(maxHops);\r\n       " +
                    " }\r\n        IFromIn_");
            
            #line 63 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromIn_");
            
            #line 63 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int minHops, int maxHops)\r\n        {\r\n            return Repeat(minHo" +
                    "ps, maxHops);\r\n        }\r\n        IFromOut_");
            
            #line 67 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromOut_");
            
            #line 67 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int maxHops)\r\n        {\r\n            return Repeat(maxHops);\r\n       " +
                    " }\r\n        IFromOut_");
            
            #line 71 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromOut_");
            
            #line 71 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int minHops, int maxHops)\r\n        {\r\n            return Repeat(minHo" +
                    "ps, maxHops);\r\n        }\r\n\r\n");
            
            #line 76 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    if (DALRelation.InEntity == DALRelation.OutEntity)
    {

            
            #line default
            #line hidden
            this.Write("        IFromAny_");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromAny_");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Alias(out ");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias)\r\n        {\r\n            return Alias(out alias);\r\n        }\r\n      " +
                    "  IFromAny_");
            
            #line 84 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromAny_");
            
            #line 84 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int maxHops)\r\n        {\r\n            return Repeat(maxHops);\r\n       " +
                    " }\r\n        IFromAny_");
            
            #line 88 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL IFromAny_");
            
            #line 88 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.Repeat(int minHops, int maxHops)\r\n        {\r\n            return Repeat(minHo" +
                    "ps, maxHops);\r\n        }\r\n");
            
            #line 92 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 96 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_IN In { get { return new ");
            
            #line 96 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_IN(this); } }\r\n        public class ");
            
            #line 97 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_IN\r\n        {\r\n            private ");
            
            #line 99 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Parent;\r\n            internal ");
            
            #line 100 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_IN(");
            
            #line 100 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL parent)\r\n            {\r\n                Parent = parent;\r\n            }\r\n\r\n");
            
            #line 105 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (Entity entity in DALRelation.InEntity.GetSubclassesOrSelf())
    {

            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 109 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node ");
            
            #line 109 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return new ");
            
            #line 109 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node(Parent, DirectionEnum.In); } }\r\n");
            
            #line 110 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public ");
            
            #line 115 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_OUT Out { get { return new ");
            
            #line 115 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_OUT(this); } }\r\n        public class ");
            
            #line 116 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_OUT\r\n        {\r\n            private ");
            
            #line 118 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Parent;\r\n            internal ");
            
            #line 119 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_OUT(");
            
            #line 119 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL parent)\r\n            {\r\n                Parent = parent;\r\n            }\r\n\r\n");
            
            #line 124 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (Entity entity in DALRelation.OutEntity.GetSubclassesOrSelf())
    {
        if(entity.IsVirtual && DALRelation.OutEntity != entity)
        {

            
            #line default
            #line hidden
            this.Write("            [Obsolete(\"This relationship is virtual, consider making entity ");
            
            #line 130 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" concrete or exit this relationship via ");
            
            #line 130 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(".\", true)]\r\n");
            
            #line 131 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

        }

            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 134 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node ");
            
            #line 134 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return new ");
            
            #line 134 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node(Parent, DirectionEnum.Out); } }\r\n");
            
            #line 135 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 139 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    if (DALRelation.InEntity == DALRelation.OutEntity)
    {

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 144 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ANY Any { get { return new ");
            
            #line 144 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ANY(this); } }\r\n        public class ");
            
            #line 145 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ANY\r\n        {\r\n            private ");
            
            #line 147 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Parent;\r\n            internal ");
            
            #line 148 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ANY(");
            
            #line 148 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL parent)\r\n            {\r\n                Parent = parent;\r\n            }\r\n\r\n");
            
            #line 153 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (Entity entity in DALRelation.InEntity.GetSubclassesOrSelf())
    {

            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node ");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return new ");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Node(Parent, DirectionEnum.None); } }\r\n");
            
            #line 158 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 162 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public interface IFromIn_");
            
            #line 167 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL\r\n    {\r\n        IFromIn_");
            
            #line 169 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Alias(out ");
            
            #line 169 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias);\r\n        IFromIn_");
            
            #line 170 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int maxHops);\r\n        IFromIn_");
            
            #line 171 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int minHops, int maxHops);\r\n\r\n        ");
            
            #line 173 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.");
            
            #line 173 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_OUT Out { get; }\r\n    }\r\n    public interface IFromOut_");
            
            #line 175 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL\r\n    {\r\n        IFromOut_");
            
            #line 177 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Alias(out ");
            
            #line 177 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias);\r\n        IFromOut_");
            
            #line 178 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int maxHops);\r\n        IFromOut_");
            
            #line 179 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int minHops, int maxHops);\r\n\r\n        ");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_IN In { get; }\r\n    }\r\n");
            
            #line 183 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    if (DALRelation.InEntity == DALRelation.OutEntity)
    {

            
            #line default
            #line hidden
            this.Write("    public interface IFromAny_");
            
            #line 187 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL\r\n    {\r\n        IFromAny_");
            
            #line 189 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Alias(out ");
            
            #line 189 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias);\r\n        IFromAny_");
            
            #line 190 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int maxHops);\r\n        IFromAny_");
            
            #line 191 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Repeat(int minHops, int maxHops);\r\n\r\n        ");
            
            #line 193 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL.");
            
            #line 193 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ANY Any { get; }\r\n    }\r\n");
            
            #line 195 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n    public class ");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS : AliasResult\r\n    {\r\n        private ");
            
            #line 201 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL Parent;\r\n\r\n        internal ");
            
            #line 203 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS(");
            
            #line 203 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_REL parent)\r\n        {\r\n            Parent = parent;\r\n\r\n");
            
            #line 207 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResultType(attr.SystemReturnType)));
            
            #line default
            #line hidden
            this.Write("(this, \"");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Datastore.GetType().FullName.Replace("+", ".")));
            
            #line default
            #line hidden
            this.Write(".Model.Relations[\"");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("\"], ");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Datastore.GetType().FullName));
            
            #line default
            #line hidden
            this.Write(".Model.Relations[\"");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Parent.Name));
            
            #line default
            #line hidden
            this.Write("\"].Properties[\"");
            
            #line 211 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n");
            
            #line 212 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public Assignment[] Assign(");
            
            #line 217 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Properties.ToJsonNotation()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            List<Assignment> assignments = new List<Assignment>();\r" +
                    "\n");
            
            #line 220 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue) assignments.Add(new Assignment(this.");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 225 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n            return assignments.ToArray();\r\n        }\r\n\r\n");
            
            #line 232 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResultType(attr.SystemReturnType)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; } \r\n");
            
            #line 237 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }
    if (DALRelation.IsTimeDependent)
    {

            
            #line default
            #line hidden
            this.Write("\r\n        public QueryCondition[] Moment(DateTime? moment)\r\n        {\r\n          " +
                    "  return new QueryCondition[] { ");
            
            #line 245 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.StartDate));
            
            #line default
            #line hidden
            this.Write(" <= moment, ");
            
            #line 245 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.EndDate));
            
            #line default
            #line hidden
            this.Write(" > moment };\r\n        }\r\n        public QueryCondition[] Moment(DateTimeResult mo" +
                    "ment)\r\n        {\r\n            return new QueryCondition[] { ");
            
            #line 249 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.StartDate));
            
            #line default
            #line hidden
            this.Write(" <= moment, ");
            
            #line 249 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.EndDate));
            
            #line default
            #line hidden
            this.Write(" > moment };\r\n        }\r\n        public QueryCondition[] Moment(Parameter moment)" +
                    "\r\n        {\r\n            return new QueryCondition[] { ");
            
            #line 253 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.StartDate));
            
            #line default
            #line hidden
            this.Write(" <= moment, ");
            
            #line 253 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.EndDate));
            
            #line default
            #line hidden
            this.Write(" > moment };\r\n        }\r\n");
            
            #line 255 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.Query\DatastoreTemplates\Domain_Data_Relationship.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
