// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Blueprint41.DatastoreTemplates.Async
{
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Domain_Data_Entity_Abstract : GeneratorBaseAsync
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"#nullable disable
#pragma warning disable S101 // Types should be named in PascalCase
#pragma warning disable CS8981 // Names should not be lower type only
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable VSSpell001 // Spell Check

// ASYNC

using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;

using Blueprint41;
using Blueprint41.Core;
using Blueprint41.Events;
using Blueprint41.Query;
using Blueprint41.DatastoreTemplates;
using q = ");
            
            #line 27 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AnySettings.FullQueryNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 29 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.FullCRUDNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 31 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

if (DALModel.IsAbstract)
{

            
            #line default
            #line hidden
            this.Write("    public interface I");
            
            #line 35 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("OriginalData");
            
            #line 35 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Inherits is null ? "" : string.Concat(" : I", DALModel.Inherits.Name, "OriginalData")));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 37 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    foreach (Property attr in DALModel.Properties)
    {
        if (attr.IsKey)
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 43 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeReadOnlyAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 43 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 44 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }
        else if (attr.PropertyType == PropertyType.Collection || attr.IsNodeType)
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 49 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeReadOnlyAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 49 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 50 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            if (attr.EntityReturnType is not null && attr.EntityReturnType.IsAbstract)
            {
                foreach (Entity concrete in attr.EntityReturnType.GetSubclasses())
                {
                    string concreteOuterType = string.Concat("IEnumerable<", concrete.ClassName, ">");

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 57 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concreteOuterType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 57 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 57 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(concrete.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 58 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

                }
            }
        }
        else if (attr.PropertyType == PropertyType.Lookup)
        {
            if (attr.Relationship.IsTimeDependent)
            {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 67 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeReadOnlyAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 67 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 68 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 73 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeReadOnlyAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 74 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
        }
        else
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeReadOnlyAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 81 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }
    }

    if (!string.IsNullOrEmpty(DALModel.UnidentifiedProperties))
    {

            
            #line default
            #line hidden
            this.Write("        \r\n        #region Member for UnidentifiedProperties\r\n\r\n        IDictionar" +
                    "y<string, object> ");
            
            #line 91 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.UnidentifiedProperties));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n        #endregion\r\n");
            
            #line 94 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public partial interface ");
            
            #line 99 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write(" : OGM");
            
            #line 99 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join("", DALModel.GetBaseTypes().Where(item => item.IsAbstract).Select(item => string.Concat(", ", item.ClassName)).ToArray())));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 101 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    if (DALModel.NodeType is null && DALModel.GetBaseTypes().Count == 0)
    {

            
            #line default
            #line hidden
            this.Write("        string ");
            
            #line 105 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.NodeTypeName));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 106 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        #region Properties\r\n");
            
            #line 111 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    foreach (Property attr in DALModel.Properties)
    {
        if (attr.PropertyType == PropertyType.Collection || attr.IsNodeType)
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 117 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 118 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }
        else
        {
            string accessors = (attr.HideSetter) ? "get;" : "get; set;";

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 124 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeAsync));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 124 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { ");
            
            #line 124 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(accessors));
            
            #line default
            #line hidden
            this.Write(" }\r\n");
            
            #line 125 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            if (attr.PropertyType == PropertyType.Lookup && attr.Relationship.IsTimeDependent)
            {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 129 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeAsync));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 129 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("(DateTime moment);\r\n        //void Set");
            
            #line 130 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 130 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnTypeAsync));
            
            #line default
            #line hidden
            this.Write(" value, DateTime? moment);\r\n");
            
            #line 131 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n        #endregion\r\n\r\n        #region Relationship Properties\r\n");
            
            #line 140 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    foreach (var attr in DALModel.GetPropertiesOfBaseTypesAndSelf().Where(property => property.PropertyType != PropertyType.Attribute))
    {
        if (attr.PropertyType == PropertyType.Collection)
        {
            if (!attr.Relationship.IsTimeDependent)
            {
/*******************************************************************************************
***                                                                                      ***
*** NORMAL COLLECTION                                                                    ***
***                                                                                      ***
*******************************************************************************************/

            
            #line default
            #line hidden
            this.Write("\r\n        #region ");
            
            #line 154 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" (Collection)\r\n\r\n        Task<List<");
            
            #line 156 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 156 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("RelationsAsync();\r\n        Task<List<");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 157 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition> expression);\r\n        Task<List<");
            
            #line 158 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 158 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 158 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition[]> expression);\r\n        Task<List<");
            
            #line 159 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 159 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(");
            
            #line 159 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation()));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task Add");
            
            #line 160 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 160 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 160 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 160 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task Remove");
            
            #line 161 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 161 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 161 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        #endregion\r\n");
            
            #line 164 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
            else
            {
/*******************************************************************************************
***                                                                                      ***
*** TIME DEPENDENT COLLECTION                                                            ***
***                                                                                      ***
*******************************************************************************************/

            
            #line default
            #line hidden
            this.Write("\r\n        #region ");
            
            #line 175 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" (Time Dependent Collection)\r\n\r\n        Task<List<");
            
            #line 177 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 177 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("RelationsAsync();\r\n        Task<List<");
            
            #line 178 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 178 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 178 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition> expression);\r\n        Task<List<");
            
            #line 179 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 179 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 179 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition[]> expression);\r\n        Task<List<");
            
            #line 180 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 180 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(JsNotation<DateTime?> Moment = default");
            
            #line 180 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task Add");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", DateTime? moment");
            
            #line 181 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task Remove");
            
            #line 182 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToSingular()));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 182 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 182 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", DateTime? moment);\r\n\r\n        #endregion\r\n");
            
            #line 185 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
        }
        else if (attr.PropertyType == PropertyType.Lookup)
        {
            if (!attr.Relationship.IsTimeDependent)
            {
/*******************************************************************************************
***                                                                                      ***
*** NORMAL LOOKUP                                                                        ***
***                                                                                      ***
*******************************************************************************************/

            
            #line default
            #line hidden
            this.Write("\r\n        #region ");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" (Lookup)\r\n\r\n        Task<");
            
            #line 201 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 201 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("RelationAsync();\r\n        Task<");
            
            #line 202 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 202 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(Func<");
            
            #line 202 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition> expression);\r\n        Task<");
            
            #line 203 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 203 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(Func<");
            
            #line 203 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition[]> expression);\r\n        Task<");
            
            #line 204 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 204 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(");
            
            #line 204 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation()));
            
            #line default
            #line hidden
            this.Write(");\r\n        void Set");
            
            #line 205 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 205 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 205 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 205 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        #endregion\r\n");
            
            #line 208 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
            else
            {
/*******************************************************************************************
***                                                                                      ***
*** TIME DEPENDENT LOOKUP                                                                ***
***                                                                                      ***
*******************************************************************************************/

            
            #line default
            #line hidden
            this.Write("\r\n        #region ");
            
            #line 219 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" (Time Dependent Lookup)\r\n\r\n        Task<");
            
            #line 221 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 221 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("RelationAsync(DateTime? moment = null);\r\n        Task<List<");
            
            #line 222 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 222 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("RelationsAsync();\r\n        Task<");
            
            #line 223 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 223 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(DateTime? moment, Func<");
            
            #line 223 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition> expression);\r\n        Task<");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(DateTime? moment, Func<");
            
            #line 224 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition[]> expression);\r\n        Task<");
            
            #line 225 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write("> Get");
            
            #line 225 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("IfAsync(DateTime? moment");
            
            #line 225 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        Task<List<");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition> expression);\r\n        Task<List<");
            
            #line 227 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 227 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(Func<");
            
            #line 227 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(".Alias, QueryCondition[]> expression);\r\n        Task<List<");
            
            #line 228 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Name));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 228 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("WhereAsync(JsNotation<DateTime?> Moment = default");
            
            #line 228 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n        void Set");
            
            #line 229 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 229 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 229 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.ForeignEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(", DateTime? moment");
            
            #line 229 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Relationship.Properties.ToJsonNotation(attr.Relationship, true)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        #endregion\r\n");
            
            #line 232 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }
        }
    }

/*******************************************************************************************
***                                                                                      ***
*** END RELATIONSHIP PROPERTIES                                                          ***
***                                                                                      ***
*******************************************************************************************/

            
            #line default
            #line hidden
            this.Write("        #endregion\r\n\r\n");
            
            #line 245 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    if (!string.IsNullOrEmpty(DALModel.UnidentifiedProperties))
    {

            
            #line default
            #line hidden
            this.Write("        \r\n        #region Member for UnidentifiedProperties\r\n\r\n        IDictionar" +
                    "y<string, object> ");
            
            #line 252 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.UnidentifiedProperties));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n        #endregion\r\n");
            
            #line 255 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 259 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Inherits is null ? "" : "new "));
            
            #line default
            #line hidden
            this.Write("I");
            
            #line 259 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("OriginalData OriginalVersion { get; }\r\n    }\r\n\r\n    public partial class ");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write(" : OGMAbstractImpl<");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.SystemReturnType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        #region Initialize\r\n\r\n        [Obsolete]\r\n        static ");
            
            #line 267 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            Register.Types();\r\n        }\r\n\r\n        protected over" +
                    "ride void RegisterGeneratedStoredQueries()\r\n        {\r\n");
            
            #line 274 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    if (!DALModel.IsVirtual)
    {

            
            #line default
            #line hidden
            this.Write("            #region LoadByKeys\r\n            \r\n            RegisterQuery(nameof(Lo" +
                    "adByKeys), (query, alias) => query.\r\n                Where(alias.");
            
            #line 281 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.Name));
            
            #line default
            #line hidden
            this.Write(".In(Parameter.New<");
            
            #line 281 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.SystemReturnType));
            
            #line default
            #line hidden
            this.Write(">(Param0))));\r\n\r\n            #endregion\r\n\r\n");
            
            #line 285 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        foreach (Property attr in DALModel.GetPropertiesOfBaseTypesAndSelf())
        {
            if (attr.PropertyType != PropertyType.Attribute || attr.IndexType != IndexType.Unique)
                continue;

            
            #line default
            #line hidden
            this.Write("\r\n            #region LoadBy");
            
            #line 292 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            RegisterQuery(nameof(LoadBy");
            
            #line 294 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("), (query, alias) => query.\r\n                Where(alias.");
            
            #line 295 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" == Parameter.New<");
            
            #line 295 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.SystemReturnType));
            
            #line default
            #line hidden
            this.Write(">(Param0)));\r\n\r\n            #endregion\r\n");
            
            #line 298 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("            AdditionalGeneratedStoredQueries();\r\n        }\r\n");
            
            #line 304 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    foreach (Property attr in DALModel.GetPropertiesOfBaseTypesAndSelf())
    {
        if (attr.PropertyType != PropertyType.Attribute || attr.IndexType != IndexType.Unique)
            continue;

            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 310 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write(" LoadBy");
            
            #line 310 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 310 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.SystemReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 310 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return FromQuery(nameof(LoadBy");
            
            #line 312 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("), new Parameter(Param0, ");
            
            #line 312 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")).FirstOrDefault();\r\n        }\r\n");
            
            #line 314 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("        partial void AdditionalGeneratedStoredQueries();\r\n");
            
            #line 318 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    if (!DALModel.IsVirtual)
    {

            
            #line default
            #line hidden
            this.Write("        \r\n        public static Dictionary<");
            
            #line 323 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.SystemReturnType));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 323 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("> LoadByKeys(IEnumerable<");
            
            #line 323 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.SystemReturnType));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 323 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return FromQuery(nameof(LoadByKeys), new Parameter(Para" +
                    "m0, ");
            
            #line 325 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".ToArray(), typeof(");
            
            #line 325 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.SystemReturnType));
            
            #line default
            #line hidden
            this.Write("))).ToDictionary(item=> item.");
            
            #line 325 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Key.Name));
            
            #line default
            #line hidden
            this.Write(", item => item);\r\n        }\r\n\r\n        protected static void RegisterQuery(string" +
                    " name, Func<IMatchQuery, q.");
            
            #line 328 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("Alias, IWhereQuery> query)\r\n        {\r\n            q.");
            
            #line 330 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("Alias alias;\r\n\r\n            IMatchQuery matchQuery = Cypher.Match(q.Node.");
            
            #line 332 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out alias));\r\n            IWhereQuery partial = query.Invoke(matchQuery, a" +
                    "lias);\r\n            ICompiled compiled = partial.Return(alias).Compile();\r\n\r\n   " +
                    "         RegisterQuery(name, compiled);\r\n        }\r\n");
            
            #line 338 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        #endregion\r\n\r\n        private static ");
            
            #line 344 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("Members members = null;\r\n        public static ");
            
            #line 345 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("Members Members\r\n        {\r\n            get\r\n            {\r\n                if (m" +
                    "embers is null)\r\n                {\r\n                    lock (typeof(");
            
            #line 351 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("))\r\n                    {\r\n                        if (members is null)\r\n        " +
                    "                    members = new ");
            
            #line 354 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("Members();\r\n                    }\r\n                }\r\n                return memb" +
                    "ers;\r\n            }\r\n        }\r\n        public class ");
            
            #line 360 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("Members\r\n        {\r\n            internal ");
            
            #line 362 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("Members() { }\r\n\r\n");
            
            #line 364 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    foreach (Entity inherited in DALModel.GetBaseTypesAndSelf())
    {

            
            #line default
            #line hidden
            this.Write("            #region Members for interface I");
            
            #line 368 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inherited.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 370 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        foreach (Property attr in inherited.Properties)
        {

            
            #line default
            #line hidden
            this.Write("            public EntityProperty ");
            
            #line 374 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; } = ");
            
            #line 374 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Datastore.GetType().FullName.Replace("+", ".")));
            
            #line default
            #line hidden
            this.Write(".Model.Entities[\"");
            
            #line 374 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inherited.Name));
            
            #line default
            #line hidden
            this.Write("\"].Properties[\"");
            
            #line 374 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\"];\r\n");
            
            #line 375 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }

            
            #line default
            #line hidden
            this.Write("            #endregion\r\n\r\n");
            
            #line 380 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 384 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    var enumProperties = DALModel.Properties.Where(item => item.EnumValues is not null).ToList();

    if (enumProperties.Count != 0)
    {

            
            #line default
            #line hidden
            this.Write("\r\n        #region Enumerations\r\n\r\n");
            
            #line 393 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        foreach (Property attr in enumProperties)
        {
            if (attr.EnumValues is null)
                continue;

            
            #line default
            #line hidden
            this.Write("        public enum ");
            
            #line 399 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("Enum\r\n        {\r\n");
            
            #line 401 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            foreach (var value in attr.EnumValues)
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 405 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 405 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.Value));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 406 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 411 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

        }

            
            #line default
            #line hidden
            this.Write("        #endregion\r\n");
            
            #line 415 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        sealed protected override Entity GetEntity()\r\n        {\r\n            if" +
                    " (entity is null)\r\n            {\r\n                lock (typeof(");
            
            #line 423 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.ClassName));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    if (entity is null)\r\n                 " +
                    "       entity = ");
            
            #line 426 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Datastore.GetType().FullName.Replace("+", ".")));
            
            #line default
            #line hidden
            this.Write(".Model.Entities[\"");
            
            #line 426 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALModel.Name));
            
            #line default
            #line hidden
            this.Write("\"];\r\n                }\r\n            }\r\n            return entity;\r\n        }\r\n   " +
                    " }\r\n");
            
            #line 432 "C:\_CirclesArrows\blueprint41\Version 2\Blueprint41.OGM\DatastoreTemplates\Async\Domain_Data_Entity_Abstract.tt"

}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
