using System;

using Blueprint41;
using Blueprint41.Query;

namespace Domain.Data.Query
{
public partial class PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL : RELATIONSHIP, IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL, IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL	{
        public override string NEO4J_TYPE
        {
            get
            {
                return "HAS_PURCHASEORDERHEADER";
            }
        }
        public override AliasResult RelationshipAlias { get; protected set; }
        
		internal PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL(Blueprint41.Query.Node parent, DirectionEnum direction) : base(parent, direction) { }

		public PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Alias(out PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS alias)
		{
			alias = new PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS(this);
            RelationshipAlias = alias;
			return this;
		} 
		public PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int maxHops)
		{
			return Repeat(1, maxHops);
		}
		public PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int minHops, int maxHops)
		{
			return this;
		}

		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Alias(out PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS alias)
		{
			return Alias(out alias);
		}
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Alias(out PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS alias)
		{
			return Alias(out alias);
		}
		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Repeat(int maxHops)
		{
			return Repeat(maxHops);
		}
		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Repeat(int minHops, int maxHops)
		{
			return Repeat(minHops, maxHops);
		}
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Repeat(int maxHops)
		{
			return Repeat(maxHops);
		}
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.Repeat(int minHops, int maxHops)
		{
			return Repeat(minHops, maxHops);
		}


		public PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_IN In { get { return new PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_IN(this); } }
        public class PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_IN
        {
            private PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Parent;
            internal PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_IN(PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL parent)
            {
                Parent = parent;
            }

			public PurchaseOrderDetailNode PurchaseOrderDetail { get { return new PurchaseOrderDetailNode(Parent, DirectionEnum.In); } }
        }

        public PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_OUT Out { get { return new PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_OUT(this); } }
        public class PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_OUT
        {
            private PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Parent;
            internal PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_OUT(PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL parent)
            {
                Parent = parent;
            }

			public PurchaseOrderHeaderNode PurchaseOrderHeader { get { return new PurchaseOrderHeaderNode(Parent, DirectionEnum.Out); } }
        }
	}

    public interface IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL
    {
		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Alias(out PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS alias);
		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int maxHops);
		IFromIn_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int minHops, int maxHops);

        PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_OUT Out { get; }
    }
    public interface IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL
    {
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Alias(out PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS alias);
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int maxHops);
		IFromOut_PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Repeat(int minHops, int maxHops);

        PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL.PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_IN In { get; }
    }

    public class PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS : AliasResult
    {
		private PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL Parent;

        internal PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_ALIAS(PURCHASEORDERDETAIL_HAS_PURCHASEORDERHEADER_REL parent)
        {
			Parent = parent;
        }
    }
}
