// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Blueprint41.Neo4j.Refactoring.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Diagnostics;
    using Blueprint41;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_Xirqlz\blueprint41\Blueprint41\Neo4j\Refactoring\Templates\CreateIndex.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal partial class CreateIndex : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 8 "C:\_Xirqlz\blueprint41\Blueprint41\Neo4j\Refactoring\Templates\CreateIndex.tt"


    Debug.WriteLine("	executing {0} -> Create INDEX for {1}.{2}", this.GetType().Name, Entity.Name, Property.Name);

            
            #line default
            #line hidden
            this.Write("CREATE INDEX ON :");
            
            #line 12 "C:\_Xirqlz\blueprint41\Blueprint41\Neo4j\Refactoring\Templates\CreateIndex.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entity.Label.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 12 "C:\_Xirqlz\blueprint41\Blueprint41\Neo4j\Refactoring\Templates\CreateIndex.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 13 "C:\_Xirqlz\blueprint41\Blueprint41\Neo4j\Refactoring\Templates\CreateIndex.tt"


	// Template Parameters
	public Entity	Entity	 { get; set; }
	public Property Property { get; set; }


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
