// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Blueprint41.DatastoreTemplates
{
    using System;
    using System.IO;
    using System.Text;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Domain_Data_Entity_Relation : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"#pragma warning disable S101 // Types should be named in PascalCase

using System;
using System.Linq;
using System.Collections.Generic;

using Blueprint41;
using Blueprint41.Core;
using Blueprint41.Query;
using Blueprint41.DatastoreTemplates;
using q = ");
            
            #line 19 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.FullQueryNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\nusing node = ");
            
            #line 20 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.FullQueryNamespace));
            
            #line default
            #line hidden
            this.Write(".Node;\r\n\r\nnamespace ");
            
            #line 22 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Settings.FullCRUDNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Relationship: (");
            
            #line 25 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 25 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 25 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n    /// </summary>\r\n    public partial class ");
            
            #line 27 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private ");
            
            #line 29 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("(string elementId, ");
            
            #line 29 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" @in, ");
            
            #line 29 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" @out, Dictionary<string, object> properties)\r\n        {\r\n            _elementId " +
                    "= elementId;\r\n            \r\n            ");
            
            #line 33 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" = @in;\r\n            ");
            
            #line 34 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" = @out;\r\n            \r\n");
            
            #line 36 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 40 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 40 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnType));
            
            #line default
            #line hidden
            this.Write(")PersistenceProvider.CurrentPersistenceProvider.ConvertFromStoredType(typeof(");
            
            #line 40 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnType));
            
            #line default
            #line hidden
            this.Write("), properties.GetValue(\"");
            
            #line 40 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\"));\r\n");
            
            #line 41 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        private string _elementId { get; set; }\r\n\r\n        /// <summ" +
                    "ary>\r\n        /// Person (In Node)\r\n        /// </summary>\r\n        public ");
            
            #line 50 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 50 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\r\n        /// <summary>\r\n        /// Restaurant (Out Node" +
                    ")\r\n        /// </summary>\r\n        public ");
            
            #line 55 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 55 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\r\n");
            
            #line 57 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 61 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.OuterReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 61 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n");
            
            #line 62 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        public void Assign(");
            
            #line 66 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Properties.ToJsonNotation(DALRelation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var query = Transaction.CompiledQuery\r\n                " +
                    ".Match(node.");
            
            #line 69 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var inAlias).In.");
            
            #line 69 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var relAlias).Out.");
            
            #line 69 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var outAlias))\r\n                .Where(inAlias.Uid == ");
            
            #line 70 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Uid, outAlias.Uid == ");
            
            #line 70 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Uid, relAlias.ElementId == _elementId)\r\n                .Set(GetAssignments(relA" +
                    "lias))\r\n                .Compile();\r\n\r\n            var context = query.GetExecut" +
                    "ionContext();\r\n            context.Execute();\r\n\r\n            Assignment[] GetAss" +
                    "ignments(q.");
            
            #line 77 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS alias)\r\n            {\r\n                List<Assignment> assignments = new " +
                    "List<Assignment>();\r\n");
            
            #line 80 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    foreach (var attr in DALRelation.Properties)
    {
        if (DALRelation.ExcludedProperties().Contains(attr.Name))
            continue;

            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 86 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue) assignments.Add(new Assignment(alias.");
            
            #line 86 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 86 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 87 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    }

            
            #line default
            #line hidden
            this.Write("               \r\n                return assignments.ToArray();\r\n            }\r\n  " +
                    "      }\r\n        public static List<");
            
            #line 94 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("> Where(Func<");
            
            #line 94 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_CRUD_ALIAS, QueryCondition> expression)\r\n        {\r\n            var query = Tran" +
                    "saction.CompiledQuery\r\n                .Match(node.");
            
            #line 97 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var inAlias).In.");
            
            #line 97 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var relAlias).Out.");
            
            #line 97 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var outAlias))\r\n                .Where(expression.Invoke(new ");
            
            #line 98 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write(@"_CRUD_ALIAS(relAlias, inAlias, outAlias)))
                .Return(relAlias.ElementId.As(""elementId""), relAlias.Properties(""properties""), inAlias.As(""in""), outAlias.As(""out""))
                .Compile();

            return Load(query);
        }
        public static List<");
            
            #line 104 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("> Where(Func<");
            
            #line 104 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_CRUD_ALIAS, QueryCondition[]> expression)\r\n        {\r\n            var query = Tr" +
                    "ansaction.CompiledQuery\r\n                .Match(node.");
            
            #line 107 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var inAlias).In.");
            
            #line 107 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var relAlias).Out.");
            
            #line 107 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(".Alias(out var outAlias))\r\n                .Where(expression.Invoke(new ");
            
            #line 108 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write(@"_CRUD_ALIAS(relAlias, inAlias, outAlias)))
                .Return(relAlias.ElementId.As(""elementId""), relAlias.Properties(""properties""), inAlias.As(""in""), outAlias.As(""out""))
                .Compile();

            return Load(query);
        }
        public static List<");
            
            #line 114 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("> Where(");
            
            #line 114 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Properties.ToJsonNotation()));
            
            #line default
            #line hidden
            this.Write(", JsNotation<");
            
            #line 114 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("> InNode = default, JsNotation<");
            
            #line 114 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("> OutNode = default)\r\n        {\r\n            return Where(delegate(");
            
            #line 116 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_CRUD_ALIAS alias)\r\n            {\r\n                List<QueryCondition> condition" +
                    "s = new List<QueryCondition>();\r\n\r\n");
            
            #line 120 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    foreach (var attr in DALRelation.Properties)
    {
        if (attr.SystemReturnType.IsEnum)
        {

            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 126 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue) conditions.Add(alias.");
            
            #line 126 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 126 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".Value?.ToString());\r\n");
            
            #line 127 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 132 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue) conditions.Add(alias.");
            
            #line 132 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 132 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(".Value);\r\n");
            
            #line 133 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("                if (InNode.HasValue) conditions.Add(alias.");
            
            #line 137 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("(InNode.Value));\r\n                if (OutNode.HasValue) conditions.Add(alias.");
            
            #line 138 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("(OutNode.Value));\r\n\r\n                return conditions.ToArray();\r\n            })" +
                    ";\r\n        }\r\n        private static List<");
            
            #line 143 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("> Load(ICompiled query)\r\n        {\r\n            var context = query.GetExecutionC" +
                    "ontext();\r\n            var results = context.Execute(NodeMapping.AsWritableEntit" +
                    "y);\r\n\r\n            return results.Select(result => new ");
            
            #line 148 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("(\r\n                result.elementId,\r\n                result.@in,\r\n              " +
                    "  result.@out,\r\n                result.properties\r\n            )).ToList();\r\n   " +
                    "     }\r\n");
            
            #line 155 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    var enumProperties = DALRelation.Properties.Where(item => item.EnumValues is not null).ToList();

    if (enumProperties.Count != 0)
    {

            
            #line default
            #line hidden
            this.Write("\r\n        #region Enumerations\r\n\r\n");
            
            #line 164 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

        foreach (Property attr in enumProperties)
        {
            if (attr.EnumValues is null)
                continue;

            
            #line default
            #line hidden
            this.Write("        public enum ");
            
            #line 170 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("Enum\r\n        {\r\n");
            
            #line 172 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

            foreach (var value in attr.EnumValues)
            {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 176 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 176 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.Value));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 177 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 182 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

        }

            
            #line default
            #line hidden
            this.Write("        #endregion\r\n");
            
            #line 186 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        public static Relationship Relationship => Threadsafe.LazyInit(ref _rel" +
                    "ationship, () => ");
            
            #line 190 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Datastore.GetType().FullName.Replace("+", ".")));
            
            #line default
            #line hidden
            this.Write(".Model.Relations[\"");
            
            #line 190 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n        private static Relationship _relationship = null;\r\n    }\r\n\r\n    ///" +
                    " <summary>\r\n    /// CRUD Specific alias for relationship: (");
            
            #line 195 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 195 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 195 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n    /// </summary>\r\n    public partial class ");
            
            #line 197 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_CRUD_ALIAS\r\n    {\r\n        internal ");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_CRUD_ALIAS(q.");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS relAlias, q.");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("Alias inAlias, q.");
            
            #line 199 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("Alias outAlias)\r\n        {\r\n            _relAlias = relAlias;\r\n            _inAli" +
                    "as = inAlias;\r\n            _outAlias = outAlias;\r\n        }\r\n\r\n");
            
            #line 206 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    foreach (var attr in DALRelation.Properties)
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 210 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResultType(attr.SystemReturnType)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 210 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n                if (_");
            
            #line 214 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" is null)\r\n                    _");
            
            #line 215 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = _relAlias.");
            
            #line 215 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n                return _");
            
            #line 217 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n        }\r\n        private ");
            
            #line 220 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetResultType(attr.SystemReturnType)));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 220 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attr.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n");
            
            #line 221 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// ");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" in-node: (");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 226 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where in-" +
                    "node is the given ");
            
            #line 229 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 231 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 231 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 231 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _inAlias.Uid == ");
            
            #line 233 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Uid;\r\n        }\r\n        /// <summary>\r\n        /// ");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" in-node: (");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 236 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where in-" +
                    "node is in the given set of ");
            
            #line 239 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 241 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural()));
            
            #line default
            #line hidden
            this.Write("(IEnumerable<");
            
            #line 241 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 241 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _inAlias.Uid.In(");
            
            #line 243 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Select(item => item.Uid));\r\n        }\r\n        /// <summary>\r\n        /// ");
            
            #line 246 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(" in-node: (");
            
            #line 246 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 246 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 246 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where in-" +
                    "node is in the given set of ");
            
            #line 249 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 251 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural()));
            
            #line default
            #line hidden
            this.Write("(params ");
            
            #line 251 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("[] ");
            
            #line 251 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _inAlias.Uid.In(");
            
            #line 253 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Select(item => item.Uid));\r\n        }\r\n\r\n        /// <summary>\r\n        /// ");
            
            #line 257 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" out-node: (");
            
            #line 257 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 257 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 257 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where out" +
                    "-node is the given ");
            
            #line 260 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 262 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _outAlias.Uid == ");
            
            #line 264 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Uid;\r\n        }\r\n        /// <summary>\r\n        /// ");
            
            #line 267 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" out-node: (");
            
            #line 267 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 267 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 267 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where out" +
                    "-node is in the given set of ");
            
            #line 270 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 272 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural()));
            
            #line default
            #line hidden
            this.Write("(IEnumerable<");
            
            #line 272 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 272 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _outAlias.Uid.In(");
            
            #line 274 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Select(item => item.Uid));\r\n        }\r\n        /// <summary>\r\n        /// ");
            
            #line 277 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(" out-node: (");
            
            #line 277 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write(")-[");
            
            #line 277 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("]->(");
            
            #line 277 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n        /// </summary>\r\n        /// <returns>\r\n        /// Condition where out" +
                    "-node is in the given set of ");
            
            #line 280 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToTitleCase().ToLowerCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </returns>\r\n        public QueryCondition ");
            
            #line 282 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural()));
            
            #line default
            #line hidden
            this.Write("(params ");
            
            #line 282 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("[] ");
            
            #line 282 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return _outAlias.Uid.In(");
            
            #line 284 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name.ToPlural().ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".Select(item => item.Uid));\r\n        }\r\n\r\n        private readonly q.");
            
            #line 287 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("_ALIAS _relAlias;\r\n        private readonly q.");
            
            #line 288 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.InEntity.Name));
            
            #line default
            #line hidden
            this.Write("Alias _inAlias;\r\n        private readonly q.");
            
            #line 289 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.OutEntity.Name));
            
            #line default
            #line hidden
            this.Write("Alias _outAlias;\r\n    }\r\n\r\n    public static partial class RelationshipAssignment" +
                    "Extensions\r\n    {\r\n        public static void Assign(this IEnumerable<");
            
            #line 294 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Name));
            
            #line default
            #line hidden
            this.Write("> @this");
            
            #line 294 "C:\_CirclesArrows\blueprint41\Blueprint41\DatastoreTemplates\Domain_Data_Entity_Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DALRelation.Properties.ToJsonNotation(DALRelation, true)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            throw new NotImplementedException();\r\n        }\r\n    }\r" +
                    "\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
